### ISSUE TITLE
尝试hook art::ArtMethod:invoke报错

### ISSUE THREAD

**Issue by Cr1ft** [zhuotong/Android_InlineHook#4]
尝试hook art::ArtMethod:invoke报错

>    --------- beginning of crash
>2021-12-28 07:52:51.329 14444-14444/? A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x7ffbd5aff0 in tid 14444 >> 
(.zhuotong.myihk)

堆栈信息如下
![aaaa](https://i.bmp.ovh/imgs/2021/12/4d10304a2b4d24ef.png)

我发现hook确实生效了，但是运行一段时间会闪退
定义invoke，实现invoke
![](https://i.bmp.ovh/imgs/2021/12/6785332e32103094.png)
hook代码的实现
![](https://i.bmp.ovh/imgs/2021/12/c801acfb86872640.png)
运行结果
![](https://i.bmp.ovh/imgs/2021/12/1786761f1b7e436e.png)

是不是不这个hook不是线程安全的。

**Comment by zhuotong** [comment]
诚聘网络兼职工资日结!还不错~详情请登陆招聘网站http://dcrxzfiko.cn?2

**Comment by Cr1ft** [comment]
想问一下，hook 类函数时定义自己的函数指针需要吧this指针定义上去吗，还是hook框架会自己处理好呢？感谢大佬

**Comment by Cr1ft** [comment]
经过我的尝试，我发发现是我错了，1.在hook后使用了源函数指针调用，导致‘死循环’，需要使用getOriFunByHkFun获取备份的原函数指针完成原函数的调用  2.在hook类函数的时候需要定义this指针，不然会报错。

**Comment by zhuotong** [comment]
> 经过我的尝试，我发现是我错了，1.在hook后使用了源函数指针，导致'死循环'，需要使用getOriFunByHkFun获取备份的原函数追踪原函数的调用2.在hook类函数的时候需要定义这个指针，巧会报错。

不错，能自己找到问题并解决就是学到了
