### ISSUE TITLE
一些其它问题

### ISSUE THREAD

**Issue by XMDS** [zhuotong/Android_InlineHook#6]
首次非常感谢您的这个项目。尤其是写了很长的中文说明，详细说明了原理。非常感谢。
我有2个问题需要询问您。

1. 您的内联hook项目和Cydia Substrate Hook 兼容吗？
我知道不应该使用多个hook框架来用于一个项目。但我不得不这么做，我在为一个热门的安卓游戏编写动态库插件，它基本就是作弊功能和拓展其它新功能等。问题在于，编写者非常多。我们很多插件需要对同一个函数实现hook，但是大多数插件使用相同的Cydia Substrate Hook 框架实现hook，它们很好的Thumb模式下使用，并且支持同一个函数的多次hook。那么如果我使用您的hook项目，但它和Cydia Substrate Hook 实现hook同一个函数，它们能兼容吗？(orig原函数指针会保存来自于上一次hook的新函数地址吗，在我们的项目，并不需要unhook，hook一直存在。)

2. 如何申请空闲的内存？
您在说明中提到了BL BLX跳转范围问题，例如在ARM/Thumb下只支持±16M和±8M的范围跳转。如何申请被hook函数所在库的内存空间上的空闲内存，在这个范围内？

再次感谢您写的说明！

**Comment by zhuotong** [comment]
> 

1. 理论上是可以兼容的，如果出现备份、跳板指令不一致，以及进而导致指令修复不正确的问题，其实可以按照Cydia Substrate的指令长度、内容实现即可。都是开源的(github上的Cydia Substrate可能是很久以前的版本，是否官方开源不确定)，对比异同，修复即可。
2. 例如mmap指定起始基址，或者搜索so中的未使用的空间，比如so为了内存对齐之类的会加一些padding，解析elf数据结构，确定padding地址、大小，利用padding做跳板。

**Comment by XMDS** [comment]
感谢您的解答。可能我回复的有点晚了。我使用了您的项目，对于在函数头部hook和中间一些位置的hook它完美工作。但它理论上可能百分百支持任意位置hook吗？

**Comment by zhuotong** [comment]
诚聘网络兼职工资日结!还不错~详情请登陆招聘网站http://dcrxzfiko.cn?2

**Comment by zhuotong** [comment]
诚聘网络兼职工资日结!还不错~详情请登陆招聘网站http://dcrxzfiko.cn?2

**Comment by zhuotong** [comment]
> 感谢您的解答。可能我回复的有点晚了。我使用了您的项目，对于在函数头部hook和中间一些位置的hook它完美工作。但它理论上可能百分百支持任意位置hook吗？

不能百分百任意位置hook。最明显的一个问题就是跳板指令长度的问题，如果长度超过了该函数的长度则可能覆盖下一个函数或者数据，可能造成未知错误。其次的问题是任意位置hook需要做好指令修复，可能你备份的几条指令中需要你对pc寄存器相关的部分进行修复，或者可能你备份的几条指令和整个函数有很强的上下文的联系，可能无法修复等。
